### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by devjva** [saty932/cordova-plugin-autostart-permission#1]
AutoStartPermission.java:56: error: local variable callbackContext is accessed from within inner class; needs to be declared final
1>MSBUILD : cordova-build error :  addAutoStartup(callbackContext);

**Comment by saty932** [comment]
@devjva If would be good if you provide more details Like which version of android you are using cordova version ionic version.

**Comment by devjva** [comment]
Cordova-android 5.2.1
Android device: 5.1.1

tks for your reply

**Comment by saty932** [comment]
Updated code check once and let me know.
Sorry for late reply was busy..
